### ISSUE TITLE
Install script broken

### ISSUE THREAD

**Issue by ouya99** [ConsensusGroup/Haystack#19]
Current install script for Mac (tested on a Macbook Air 2014, Sierra) does not install all packages nor/or does it find all of them

see output after following Readme's installation guide

`(base) Air:HayStack_Client alexander$ python2 main.py 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from HayStack_API import HayStack, Run_HayStack_Client
  File "/Users/alexander/Dev/Haystack/HayStack_Client/HayStack_API.py", line 6, in <module>
    from DynamicPublicLedger_Module import Dynamic_Public_Ledger
  File "/Users/alexander/Dev/Haystack/HayStack_Client/DynamicPublicLedger_Module.py", line 6, in <module>
    from User_Modules import User_Profile
  File "/Users/alexander/Dev/Haystack/HayStack_Client/User_Modules.py", line 8, in <module>
    from IOTA_Module import Seed_Generator
  File "/Users/alexander/Dev/Haystack/HayStack_Client/IOTA_Module.py", line 6, in <module>
    from iota import TryteString, Address, ProposedBundle, ProposedTransaction, Bundle
ImportError: No module named iota`

**Comment by ouya99** [comment]
same error on a Ubuntu Linux system using Python2.7

**Comment by woywoy123** [comment]
It doesn't work for Ubuntu? I am currently trying to fix the MacOS issue.

**Comment by ouya99** [comment]
same issue: "no module iota found".

**Comment by woywoy123** [comment]
Updated the version of the installer script. With MacOS it should work better now since I switched back to brew. As for the linux issue, I managed to reproduce the error and found out it works only when you rerun the installer twice. Not sure why so I will work on resolving this.

**Comment by ouya99** [comment]
tested on MacOS

 sh Installer_Script_Linux_OSX.sh 
==> You are using macOS 10.12.
==> We (and Apple) do not provide support for this old version.
This installation may not succeed.
After installation, you will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 8ebfc923f Merge pull request #6792 from EricFromCanada/issue-template-update
remote: Repository not found.
fatal: repository 'https://github.com/Homebrew/homebrew-dupes/' not found

**Comment by woywoy123** [comment]
Use bash instead of sh

**Comment by ouya99** [comment]
same error with bash, seems my macOS is outdated

**Comment by woywoy123** [comment]
Check your Discord.

**Comment by ouya99** [comment]
pip -> pip2 in install script fixed issue
